export interface CandidateAuditRecord {
  prn: string;
  claimedName: string;
  claimedCgpa: number;
  onChainName: string;
  onChainCgpa: number;
  onChainUniversity: string;
  status: "AUTHENTIC" | "DISCREPANCY" | "UNREGISTERED";
  flag: string;
}

export const INITIAL_AUDIT_CANDIDATES: CandidateAuditRecord[] = [
  // 50 Batch Students (Authentic On-Chain Matches)
  {
    prn: "PRN20240001",
    claimedName: "Aarav Sharma",
    claimedCgpa: 9.42,
    onChainName: "Aarav Sharma",
    onChainCgpa: 9.42,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240002",
    claimedName: "Ananya Malhotra",
    claimedCgpa: 9.15,
    onChainName: "Ananya Malhotra",
    onChainCgpa: 9.15,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240003",
    claimedName: "Rohan Kulkarni",
    claimedCgpa: 8.24,
    onChainName: "Rohan Kulkarni",
    onChainCgpa: 8.24,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240004",
    claimedName: "Pooja Patil",
    claimedCgpa: 8.65,
    onChainName: "Pooja Patil",
    onChainCgpa: 8.65,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240005",
    claimedName: "Siddharth Joshi",
    claimedCgpa: 8.89,
    onChainName: "Siddharth Joshi",
    onChainCgpa: 8.89,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240006",
    claimedName: "Neha Kulkarni",
    claimedCgpa: 9.05,
    onChainName: "Neha Kulkarni",
    onChainCgpa: 9.05,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240007",
    claimedName: "Aditya Pawar",
    claimedCgpa: 7.92,
    onChainName: "Aditya Pawar",
    onChainCgpa: 7.92,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240008",
    claimedName: "Riya Sen",
    claimedCgpa: 8.14,
    onChainName: "Riya Sen",
    onChainCgpa: 8.14,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240009",
    claimedName: "Kunal Verma",
    claimedCgpa: 8.76,
    onChainName: "Kunal Verma",
    onChainCgpa: 8.76,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240010",
    claimedName: "Isha Gupta",
    claimedCgpa: 9.68,
    onChainName: "Isha Gupta",
    onChainCgpa: 9.68,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240011",
    claimedName: "Vikram Shinde",
    claimedCgpa: 8.35,
    onChainName: "Vikram Shinde",
    onChainCgpa: 8.35,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240012",
    claimedName: "Sneha Jagtap",
    claimedCgpa: 9.28,
    onChainName: "Sneha Jagtap",
    onChainCgpa: 9.28,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240013",
    claimedName: "Gaurav More",
    claimedCgpa: 7.82,
    onChainName: "Gaurav More",
    onChainCgpa: 7.82,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240014",
    claimedName: "Tanvi Bhosale",
    claimedCgpa: 8.91,
    onChainName: "Tanvi Bhosale",
    onChainCgpa: 8.91,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240015",
    claimedName: "Omkar Chavan",
    claimedCgpa: 8.54,
    onChainName: "Omkar Chavan",
    onChainCgpa: 8.54,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240016",
    claimedName: "Shruti Jadhav",
    claimedCgpa: 8.78,
    onChainName: "Shruti Jadhav",
    onChainCgpa: 8.78,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240017",
    claimedName: "Pranav Kale",
    claimedCgpa: 7.65,
    onChainName: "Pranav Kale",
    onChainCgpa: 7.65,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240018",
    claimedName: "Divya Rathod",
    claimedCgpa: 9.32,
    onChainName: "Divya Rathod",
    onChainCgpa: 9.32,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240019",
    claimedName: "Abhishek Gaikwad",
    claimedCgpa: 8.44,
    onChainName: "Abhishek Gaikwad",
    onChainCgpa: 8.44,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240020",
    claimedName: "Meera Nair",
    claimedCgpa: 8.98,
    onChainName: "Meera Nair",
    onChainCgpa: 8.98,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240021",
    claimedName: "Yash Salunke",
    claimedCgpa: 8.12,
    onChainName: "Yash Salunke",
    onChainCgpa: 8.12,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240022",
    claimedName: "Kavya Iyer",
    claimedCgpa: 9.55,
    onChainName: "Kavya Iyer",
    onChainCgpa: 9.55,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240023",
    claimedName: "Saurabh Mane",
    claimedCgpa: 7.74,
    onChainName: "Saurabh Mane",
    onChainCgpa: 7.74,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240024",
    claimedName: "Priyanka Thorat",
    claimedCgpa: 8.08,
    onChainName: "Priyanka Thorat",
    onChainCgpa: 8.08,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240025",
    claimedName: "Harsh Vardhan",
    claimedCgpa: 8.82,
    onChainName: "Harsh Vardhan",
    onChainCgpa: 8.82,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240026",
    claimedName: "Aishwarya Rao",
    claimedCgpa: 9.21,
    onChainName: "Aishwarya Rao",
    onChainCgpa: 9.21,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240027",
    claimedName: "Nikhil Mohite",
    claimedCgpa: 8.47,
    onChainName: "Nikhil Mohite",
    onChainCgpa: 8.47,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240028",
    claimedName: "Sayali Ghorpade",
    claimedCgpa: 8.63,
    onChainName: "Sayali Ghorpade",
    onChainCgpa: 8.63,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240029",
    claimedName: "Ajay Solanke",
    claimedCgpa: 7.88,
    onChainName: "Ajay Solanke",
    onChainCgpa: 7.88,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240030",
    claimedName: "Shweta Kadam",
    claimedCgpa: 9.12,
    onChainName: "Shweta Kadam",
    onChainCgpa: 9.12,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240031",
    claimedName: "Akash Shirsat",
    claimedCgpa: 7.95,
    onChainName: "Akash Shirsat",
    onChainCgpa: 7.95,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240032",
    claimedName: "Pallavi Date",
    claimedCgpa: 8.72,
    onChainName: "Pallavi Date",
    onChainCgpa: 8.72,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240033",
    claimedName: "Rahul Sonawane",
    claimedCgpa: 8.61,
    onChainName: "Rahul Sonawane",
    onChainCgpa: 8.61,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240034",
    claimedName: "Gayatri Mule",
    claimedCgpa: 9.40,
    onChainName: "Gayatri Mule",
    onChainCgpa: 9.40,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240035",
    claimedName: "Tejas Wagh",
    claimedCgpa: 8.05,
    onChainName: "Tejas Wagh",
    onChainCgpa: 8.05,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240036",
    claimedName: "Sanjana Bagul",
    claimedCgpa: 8.84,
    onChainName: "Sanjana Bagul",
    onChainCgpa: 8.84,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240037",
    claimedName: "Deepak Bhalerao",
    claimedCgpa: 8.29,
    onChainName: "Deepak Bhalerao",
    onChainCgpa: 8.29,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240038",
    claimedName: "Mansi Mahajan",
    claimedCgpa: 9.36,
    onChainName: "Mansi Mahajan",
    onChainCgpa: 9.36,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240039",
    claimedName: "Sumit Khade",
    claimedCgpa: 7.79,
    onChainName: "Sumit Khade",
    onChainCgpa: 7.79,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240040",
    claimedName: "Ruchira Ghodke",
    claimedCgpa: 9.18,
    onChainName: "Ruchira Ghodke",
    onChainCgpa: 9.18,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240041",
    claimedName: "Manish Ghuge",
    claimedCgpa: 7.68,
    onChainName: "Manish Ghuge",
    onChainCgpa: 7.68,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240042",
    claimedName: "Vaishnavi Tambe",
    claimedCgpa: 9.47,
    onChainName: "Vaishnavi Tambe",
    onChainCgpa: 9.47,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240043",
    claimedName: "Chetan Narwade",
    claimedCgpa: 8.19,
    onChainName: "Chetan Narwade",
    onChainCgpa: 8.19,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240044",
    claimedName: "Madhuri Shelke",
    claimedCgpa: 8.75,
    onChainName: "Madhuri Shelke",
    onChainCgpa: 8.75,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240045",
    claimedName: "Karthik Pillai",
    claimedCgpa: 8.93,
    onChainName: "Karthik Pillai",
    onChainCgpa: 8.93,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240046",
    claimedName: "Ankita Landge",
    claimedCgpa: 8.11,
    onChainName: "Ankita Landge",
    onChainCgpa: 8.11,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240047",
    claimedName: "Sagar Gunjal",
    claimedCgpa: 8.88,
    onChainName: "Sagar Gunjal",
    onChainCgpa: 8.88,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240048",
    claimedName: "Pooja Khandare",
    claimedCgpa: 8.52,
    onChainName: "Pooja Khandare",
    onChainCgpa: 8.52,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240049",
    claimedName: "Vivek Dandge",
    claimedCgpa: 8.22,
    onChainName: "Vivek Dandge",
    onChainCgpa: 8.22,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240050",
    claimedName: "Radhika Kute",
    claimedCgpa: 9.75,
    onChainName: "Radhika Kute",
    onChainCgpa: 9.75,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },

  // Second Batch Students (PRN20240051 - PRN20240060)
  {
    prn: "PRN20240051",
    claimedName: "Aayush Deshpande",
    claimedCgpa: 9.35,
    onChainName: "Aayush Deshpande",
    onChainCgpa: 9.35,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240052",
    claimedName: "Mitali Kulkarni",
    claimedCgpa: 9.12,
    onChainName: "Mitali Kulkarni",
    onChainCgpa: 9.12,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },
  {
    prn: "PRN20240053",
    claimedName: "Sanket Shinde",
    claimedCgpa: 8.45,
    onChainName: "Sanket Shinde",
    onChainCgpa: 8.45,
    onChainUniversity: "MGM University",
    status: "AUTHENTIC",
    flag: "Exact On-Chain Match",
  },

  // Realistic Discrepancy Controls (Tampered Claims Detected On-Chain)
  {
    prn: "PRN20240003-DISC",
    claimedName: "Rohan Kulkarni",
    claimedCgpa: 9.40,
    onChainName: "Rohan Kulkarni",
    onChainCgpa: 8.24,
    onChainUniversity: "MGM University",
    status: "DISCREPANCY",
    flag: "Inflated CGPA (+1.16 higher than on-chain record)",
  },
  {
    prn: "PRN20240007-DISC",
    claimedName: "Aditya Pawar",
    claimedCgpa: 8.90,
    onChainName: "Aditya Pawar",
    onChainCgpa: 7.92,
    onChainUniversity: "MGM University",
    status: "DISCREPANCY",
    flag: "Inflated CGPA (+0.98 higher than on-chain record)",
  },
  {
    prn: "PRN20240017-DISC",
    claimedName: "Pranav Kale",
    claimedCgpa: 8.50,
    onChainName: "Pranav Kale",
    onChainCgpa: 7.65,
    onChainUniversity: "MGM University",
    status: "DISCREPANCY",
    flag: "Inflated CGPA (+0.85 higher than on-chain record)",
  },

  // Realistic Forged / Unregistered Controls (Fake Certificates)
  {
    prn: "PRN99990001",
    claimedName: "Vikram Malhotra",
    claimedCgpa: 9.90,
    onChainName: "—",
    onChainCgpa: 0,
    onChainUniversity: "—",
    status: "UNREGISTERED",
    flag: "Forged PRN / No On-Chain Merkle Record",
  },
  {
    prn: "PRN99990002",
    claimedName: "Rajesh Khanna",
    claimedCgpa: 9.20,
    onChainName: "—",
    onChainCgpa: 0,
    onChainUniversity: "—",
    status: "UNREGISTERED",
    flag: "Unregistered Candidate / Unanchored Degree",
  },
];
